Repository kyj4327/DevBox, pull requests merged in 2024-10, with the labels that each got.

#251 [yerim] → [develop] merge
  devbox_client/src/components/DevBox.css
  devbox_client/src/components/DevBox.jsx
  devbox_client/src/components/Header.jsx
  devbox_client/src/components/InputScrollAndFocus.jsx
  devbox_client/src/components/MyPageSideBar.jsx
  devbox_client/src/components/WriteLong.jsx
  devbox_client/src/components/WriteSelect.jsx
  devbox_client/src/components/WriteShort.jsx
  devbox_client/src/pages/Main.jsx
  devbox_client/src/pages/auth/MyPage.jsx
  devbox_client/src/pages/contest/ContestList.jsx
  devbox_client/src/pages/contest/ContestUpdate.jsx
  devbox_client/src/pages/contest/ContestWrite.jsx
  devbox_client/src/pages/hiring/HiringList.jsx
  devbox_client/src/pages/hiring/HiringUpdate.jsx
  devbox_client/src/pages/hiring/HiringWrite.jsx
  devbox_client/src/pages/reference/MyReferenceList.jsx
  devbox_client/src/pages/reference/ReferenceList.jsx
  devbox_client/src/pages/reference/ReferenceUpdate.jsx
  devbox_client/src/pages/reference/ReferenceWrite.jsx
  devbox_client/src/pages/reservation/Reservation.jsx
  devbox_client/src/pages/reservation/ReservationList.jsx
  devbox_server/src/main/java/com/o2b2/devbox_server/config/SecurityConfig.java
  devbox_server/src/main/java/com/o2b2/devbox_server/reference/controller/ReferenceController.java
  devbox_server/src/main/java/com/o2b2/devbox_server/reference/repository/ReferenceRepository.java
  devbox_server/src/main/java/com/o2b2/devbox_server/user/jwt/JWTFilter.java
Labels: PullRequest

#263 [Youngjun] -> [develop] 10/2일 Merge
  devbox_client/public/index.html
  devbox_client/src/components/Button.css
  devbox_client/src/components/Button.jsx
  devbox_client/src/components/context/UserContext.jsx
  devbox_client/src/pages/auth/AuthContainer.css
  devbox_client/src/pages/auth/AuthContainer.jsx
  devbox_client/src/pages/auth/PasswordReset.jsx
  devbox_client/src/pages/gatherMate/GatherMateDetail.jsx
  devbox_client/src/pages/gatherMate/GatherMateEdit.jsx
  devbox_client/src/pages/gatherMate/GatherMateList.css
  devbox_client/src/pages/gatherMate/GatherMateList.jsx
  devbox_client/src/pages/gatherMate/GatherMateMyList.jsx
  devbox_client/src/pages/gatherMate/GatherMateWrite.jsx
  devbox_client/src/pages/notice/NoticeDetail.jsx
  devbox_client/src/pages/notice/NoticeEdit.jsx
  devbox_client/src/pages/notice/NoticeList.css
  devbox_client/src/pages/notice/NoticeList.jsx
  devbox_server/src/main/java/com/o2b2/devbox_server/user/controller/JoinController.java
  devbox_server/src/main/java/com/o2b2/devbox_server/user/repository/UserRepository.java
  devbox_server/src/main/java/com/o2b2/devbox_server/user/service/JoinService.java
Labels: PullRequest

#268 [yerim] -> [develop] merge
  devbox_client/src/components/Button.css
  devbox_client/src/components/Footer.jsx
  devbox_client/src/components/Header.css
  devbox_client/src/components/Header.jsx
  devbox_client/src/components/MyPageSideBar.jsx
  devbox_client/src/components/UserContact.jsx
  devbox_client/src/components/WriteLong.jsx
  devbox_client/src/pages/contest/ContestList.jsx
  devbox_client/src/pages/contest/ContestUpdate.jsx
  devbox_client/src/pages/contest/ContestWrite.jsx
  devbox_client/src/pages/education/EduInfo.jsx
  devbox_client/src/pages/hiring/HiringList.jsx
  devbox_client/src/pages/hiring/HiringUpdate.jsx
  devbox_client/src/pages/hiring/HiringWrite.jsx
  devbox_client/src/pages/jobInfo/JobInfoBack.jsx
  devbox_client/src/pages/jobInfo/JobInfoCloud.jsx
  devbox_client/src/pages/jobInfo/JobInfoData.jsx
  devbox_client/src/pages/jobInfo/JobInfoDevOps.jsx
  devbox_client/src/pages/jobInfo/JobInfoFront.jsx
  devbox_client/src/pages/jobInfo/JobInfoList.jsx
  devbox_client/src/pages/jobInfo/JobInfoMobile.jsx
  devbox_client/src/pages/message/MsgBell.jsx
  devbox_client/src/pages/reference/ReferenceList.jsx
  devbox_client/src/pages/reference/ReferenceUpdate.jsx
  devbox_client/src/pages/reference/ReferenceWrite.jsx
  devbox_client/src/pages/reservation/Reservation.jsx
  devbox_client/src/pages/reservation/ReservationList.jsx
  devbox_server/src/main/java/com/o2b2/devbox_server/contact/controller/ContactController.java
  devbox_server/src/main/java/com/o2b2/devbox_server/user/service/EmailService.java
Labels: PullRequest

#272 [Youngjun] -> [develop] 2024.10.04 Merge
  devbox_client/src/components/MyPageProfileEdit.css
  devbox_client/src/components/MyPageProfileEdit.jsx
  devbox_client/src/pages/auth/AuthContainer.jsx
  devbox_client/src/pages/auth/PasswordReset.css
  devbox_client/src/pages/auth/PasswordReset.jsx
  devbox_client/src/pages/gatherMate/GatherMateDetail.jsx
  devbox_client/src/pages/gatherMate/GatherMateEdit.jsx
  devbox_client/src/pages/notice/NoticeDetail.jsx
  devbox_client/src/pages/notice/NoticeEdit.jsx
  devbox_server/src/main/java/com/o2b2/devbox_server/user/controller/PasswordController.java
  devbox_server/src/main/java/com/o2b2/devbox_server/user/service/PasswordResetService.java
Labels: PullRequest

#275 [Youngjun] -> [develop] 2024.10.04 merge
  devbox_client/src/components/BoardComments.css
  devbox_client/src/components/BoardComments.jsx
  devbox_client/src/pages/greeting/GreetingList.jsx
Labels: 🎨 style, PullRequest

#277 [yerim] → [develop] merge
  devbox_client/src/assets/css/contact.css
  devbox_client/src/assets/css/reservation.css
  devbox_client/src/assets/img/banner-img-01.svg
  devbox_client/src/components/Header.css
  devbox_client/src/components/Header.jsx
  devbox_client/src/pages/contact/Contact.jsx
  devbox_client/src/pages/contest/ContestUpdate.jsx
  devbox_client/src/pages/contest/ContestWrite.jsx
  devbox_client/src/pages/hiring/HiringUpdate.jsx
  devbox_client/src/pages/hiring/HiringWrite.jsx
  devbox_client/src/pages/reference/ReferenceUpdate.jsx
  devbox_client/src/pages/reference/ReferenceWrite.jsx
  devbox_client/src/pages/reservation/Reservation.jsx
Labels: 이예림, PullRequest

#278 [Youngjun] -> [develop] 2024.10.04 금
  devbox_client/src/pages/gatherMate/GatherMateList.css
  devbox_client/src/pages/greeting/GreetingList.css
  devbox_client/src/pages/greeting/GreetingList.jsx
  devbox_server/src/main/java/com/o2b2/devbox_server/user/entity/UserEntity.java
Labels: PullRequest

#284 [Youngjun] -> [develop] 2024.10.05 (토)
  devbox_client/src/components/NotFound.css
  devbox_client/src/components/NotFound.jsx
  devbox_server/src/main/java/com/o2b2/devbox_server/user/repository/UserRepository.java
  devbox_server/src/main/java/com/o2b2/devbox_server/user/service/JoinService.java
Labels: PullRequest

#285 [yerim] → [develop] merge
  devbox_client/src/pages/reservation/Reservation.jsx
  devbox_server/src/main/java/com/o2b2/devbox_server/config/SecurityConfig.java
  devbox_server/src/main/java/com/o2b2/devbox_server/reservation/controller/ReservationController.java
  devbox_server/src/main/java/com/o2b2/devbox_server/reservation/repository/ReservationRepository.java
Labels: 이예림, PullRequest

#288 [Develop] -> [Main] 2024.10.05 (토)
  devbox_client/src/assets/css/contact.css
  devbox_client/src/assets/css/reservation.css
  devbox_client/src/assets/img/banner-img-01.svg
  devbox_client/src/components/FreeBoardComments.jsx
  devbox_client/src/components/Header.css
  devbox_client/src/components/Header.jsx
  devbox_client/src/components/NotFound.css
  devbox_client/src/components/NotFound.jsx
  devbox_client/src/pages/contact/Contact.jsx
  devbox_client/src/pages/contest/ContestUpdate.jsx
  devbox_client/src/pages/contest/ContestWrite.jsx
  devbox_client/src/pages/education/EduInfo.jsx
  devbox_client/src/pages/education/EduMain.jsx
  devbox_client/src/pages/freeboard/FreeBoardList.jsx
  devbox_client/src/pages/gatherMate/GatherMateList.css
  devbox_client/src/pages/greeting/GreetingList.css
  devbox_client/src/pages/greeting/GreetingList.jsx
  devbox_client/src/pages/hiring/HiringUpdate.jsx
  devbox_client/src/pages/hiring/HiringWrite.jsx
  devbox_client/src/pages/project/Project.jsx
  devbox_client/src/pages/reference/ReferenceUpdate.jsx
  devbox_client/src/pages/reference/ReferenceWrite.jsx
  devbox_client/src/pages/reservation/Reservation.jsx
  devbox_server/src/main/java/com/o2b2/devbox_server/config/SecurityConfig.java
  devbox_server/src/main/java/com/o2b2/devbox_server/eduInfo/controller/EduController.java
  devbox_server/src/main/java/com/o2b2/devbox_server/freeboard/entity/Comment.java
  devbox_server/src/main/java/com/o2b2/devbox_server/freeboard/entity/Post.java
  devbox_server/src/main/java/com/o2b2/devbox_server/reservation/controller/ReservationController.java
  devbox_server/src/main/java/com/o2b2/devbox_server/reservation/repository/ReservationRepository.java
  devbox_server/src/main/java/com/o2b2/devbox_server/user/entity/UserEntity.java
  devbox_server/src/main/java/com/o2b2/devbox_server/user/repository/UserRepository.java
  devbox_server/src/main/java/com/o2b2/devbox_server/user/service/JoinService.java
Labels: PullRequest

#295 [Youngjun] -> [Main] 2024.10.07 월
  devbox_client/src/pages/gatherMate/GatherMateDetail.jsx
  devbox_server/src/main/java/com/o2b2/devbox_server/gatherMate/controller/GatherMateController.java
  devbox_server/src/main/java/com/o2b2/devbox_server/gatherMate/domain/GatherMatePostEditor.java
  devbox_server/src/main/java/com/o2b2/devbox_server/gatherMate/entity/GatherMate.java
  devbox_server/src/main/java/com/o2b2/devbox_server/gatherMate/request/GatherMatePostEdit.java
  devbox_server/src/main/java/com/o2b2/devbox_server/gatherMate/service/GatherMateService.java
Labels: PullRequest

#298 [youngjun] -> [Main] 2024.10.08 (화) merge
  devbox_client/src/components/MyPageContent.jsx
  devbox_client/src/components/MyPageProfileEdit.jsx
Labels: PullRequest
